{
 "title": "OSM NS Metrics - OSM_NAME",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ns_id", "label": "NS ID", "query": "OSM_ID" }
  ]
 },
 "panels": [
  { "title": "VIM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "osm_cpu_utilization{ns_id=\"$ns_id\"}",
     "legendFormat": "NS {{ns_name}} - VNF {{vnf_member_index}} - VDU {{vdu_name}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "osm_average_memory_utilization{ns_id=\"$ns_id\"}",
     "legendFormat": "NS {{ns_name}} - VNF {{vnf_member_index}} - VDU {{vdu_name}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "pps", "label": "transmit (-) / receive (+)" }
   ],
   "targets": [
    {
     "expr": "osm_packets_received{ns_id=\"$ns_id\"}",
     "legendFormat": "VNF {{vnf_member_index}} - VDU {{vdu_name}}"
    },
    {
     "expr": "osm_packets_sent{ns_id=\"$ns_id\"}",
     "legendFormat": "VNF {{vnf_member_index}} - VDU {{vdu_name}}"
    }
   ]
  },
  { "title": "VNF Indicators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "osm_load{ns_id=\"$ns_id\"}",
     "legendFormat": "VNF {{vnf_member_index}} - VDU {{vdu_name}}"
    }
   ]
  },
  {
   "title": "Users",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "osm_users{ns_id=\"$ns_id\"}",
     "legendFormat": "VNF {{vnf_member_index}} - VDU {{vdu_name}}"
    }
   ]
  }
 ]
}