#!/bin/bash

echo "Installing python dependencies via pip..."
pip3 install kafka-python==1.4.3
pip3 install requests==2.18.*
pip3 install cherrypy==14.0.*
pip3 install jsmin==2.2.*
pip3 install jsonschema==2.6.*
pip3 install python-keystoneclient==3.15.*
pip3 install six==1.11.*
pip3 install peewee==3.1.*
pip3 install pyyaml==3.*
pip3 install prometheus_client==0.4.*
pip3 install gnocchiclient==7.0.*
echo "Installation of python dependencies finished"